/*
Dolar-Colombia.com Widget
Url: https://www.dolar-colombia.com/widgets
*/
if(!window.tracked){ window.tracked=true; (function (a, b) { a[b] || (a.FintezaCoreObject = b, a[b] = a[b] || function () { (a[b].q = a[b].q || []).push(arguments) }, a[b].l = 1 * new Date); })(window, "fz"); (function(){function J(){var b=window;b&&b.addEventListener("hashchange",function(){f.routePage();f.lead(f._websiteId)})}function K(){var b=window,a;b&&(a=b.document&&b.document.body)&&a.addEventListener("click",function(a){var c=a.target,e,g;if(c&&1===c.nodeType&&c.tagName&&"a"===c.tagName.toLowerCase()&&(g=c.getAttribute("target"),e=c.getAttribute("href"),L(e))){if(!g||"_self"===g||"_parent"===g||"_top"===g)return a.preventDefault&&a.preventDefault(),f.leave(f._websiteId,e,function(){g&&"_self"!==
g?"_top"===g?b.top.location.href=e:"_parent"===g&&(b.parent.location.href=e):b.location.href=e});f.leave(f._websiteId,e)}})}function M(b){var a=0,c=setInterval(function(){var d;w&&(a+=1E3);if(a/15E3===Math.floor(a/15E3)&&(d=a/1E3,q(l("https://content.mql5.com/st",m({id:f._websiteId,tracking_event:"Page+Active+Timer+"+d,pg_act:d}))),!b)){clearInterval(c);return}12E4<=a&&clearInterval(c)},1E3)}function x(){var b=[],a,c,d,e=[],g=[],f=[];for(c in k)k.hasOwnProperty(c)&&(a=k[c],!a.data&&!a.dataLoading&&(a.dataLoading=
!0,b.push(c),a=document.getElementById(c)))&&(e.push(encodeURIComponent(a.getAttribute("data-utm-source")||"")),g.push(encodeURIComponent(a.getAttribute("data-utm-campaign")||"")),f.push(encodeURIComponent(a.getAttribute("data-server")||"")));if(b.length){b={tz_offset:h.tz_offset,ids:b.join(",")};c=!1;a=0;for(d=e.length;a<d;a++)e[a]&&(c=!0);c&&(b.utm_source=e.join(","));c=!1;a=0;for(d=g.length;a<d;a++)g[a]&&(c=!0);c&&(b.utm_campaign=g.join(","));c=!1;a=0;for(d=f.length;a<d;a++)f[a]&&(c=!0);c&&(b.server=
f.join(","));g=m(b);e=document.createElement("script");e.async=!0;e.src=l("https://content.mql5.com/rq",g||{});(g=document.getElementsByTagName("script")[0])?g.parentNode.insertBefore(e,g):document.head.appendChild(e)}}function z(b){var a;if(b&&(a=k&&k[b]&&k[b].data||{},b=document.getElementById(b),a&&b))if(a.format&56){var c,d,e;if(b&&a){c=document.createElement("iframe");n&&n.length||(window.addEventListener?window.addEventListener("message",A,!1):window.attachEvent&&window.attachEvent("onmessage",A));
n||(n=[]);n.push(c);c.width=0<a.w?a.w:"100%";c.height=a.h||0;e={link:a.link,a:a.a,s:a.s,v:a.v,w:c.width,h:c.height,r:window.location,id:a.zone,uid:a.uid};if(d=b.getAttribute("data"))e.custom=d;c.frameBorder=0;c.setAttribute("style","vertical-align:top;max-width:100% !important");c.scrolling="no";c._id=a.zone;c._advert_id=a.a;c._uid=a.uid;c.onload=B;c.src=a.format&32?a.iframe:l("https://content.mql5.com/sh/"+a.name+"/",e);c.style.display="block";a.format&16?(d=document.createElement("a"),d.target="_blank",
d.href=l("https://content.mql5.com/go",m({link:a.link,a:a.a,s:a.s,v:a.v,id:a.zone,uid:a.uid})),d.style.display="inline-block",c.style.pointerEvents="none",d.appendChild(c),b.appendChild(d)):b.appendChild(c);a.tl&&q(a.tl)}}else C(b,a)}function C(b,a){var c,d,e;a&&(c=a.img,c||(c=a.img=new Image,c.onload=B,c.src="https://content.mql5.com/si/"+a.name,c.height&&(c.height=a.h),a.w&&(c.width=a.w,c.style.width=a.w+"px"),c._id=a.zone,c._advert_id=a.a,c._uid=a.uid,c._width=a.w||null,c._height=a.h||null),b&&(d=document.createElement("a"),
d.target="_blank",d.href=l("https://content.mql5.com/go",m({link:a.link,a:a.a,s:a.s,v:a.v,id:a.zone,uid:a.uid})),e=c.style,e.overflow="hidden",e.verticalAlign="top",e.height="auto",e.border="0",d.appendChild(c),b.appendChild(d),a.tl&&q(a.tl)))}function B(){q(l("https://content.mql5.com/wh",m({id:this._id,a:this._advert_id,uid:this._uid})));this._width&&(this.width=this._width,this.style.width=this._width+"px");this._height&&(this.height=this._height)}function L(b){return b?0===b.indexOf("http://")||0===b.indexOf("https://")?
0!==b.indexOf(window.location.origin):!1:!1}function D(){var b=window.document,a=window.ia_document,c=-(new Date).getTimezoneOffset(),d;d={};var e,g,f,h;e=["https://widget.dolar-colombia.com"];if(1>=e.length)d={};else for(e=e[1].split("#"),e=e[0].split("&"),f=0,h=e.length;f<h;f++)if(g=e[f])g=g.split("="),1>=g.length||(d[decodeURIComponent(g[0])]=decodeURIComponent(g[1]));h=b.referrer||"";e=b.title||"";!h&&a&&a.referrer&&(h=a.referrer);!e&&a&&a.title&&(e=a.title);a=window.location.origin;b=b.domain||
"";f=h;h=-1<h.indexOf("://")?h.split("/")[2]:h.split("/")[0];h=h.split(":")[0];h=h.split("?")[0];var k=window.screen;k?(g=k.width||0,k=k.height||0,g=g&&k?g+"x"+k:""):g="";return{tz_offset:c,origin:a,uri:"https://widget.dolar-colombia.com",domain:b,referrer:f,referrer_domain:h||"",title:e,screen_res:g,hdpi:1.5<=window.devicePixelRatio||window.matchMedia&&window.matchMedia("(-webkit-min-device-pixel-ratio: 1.5),(min--moz-device-pixel-ratio: 1.5),(-o-min-device-pixel-ratio: 3/2),(min-resolution: 1.5dppx)").matches?
!0:!1,utm_source:d.utm_source||"",utm_campaign:d.utm_campaign||"",utm_medium:d.utm_medium||"",utm_term:d.utm_term||"",utm_content:d.utm_content||"",s1:d.s1||"",s2:d.s2||"",s3:d.s3||"",s4:d.s4||"",s5:d.s5||"",s6:d.s6||"",s7:d.s7||"",s8:d.s8||"",s9:d.s9||"",s10:d.s10||"",s11:d.s11||"",s12:d.s12||"",s13:d.s13||"",s14:d.s14||"",s15:d.s15||"",s16:d.s16||""}}function r(){var b=new Date,a=new Date(b.getTime()+18E5),b=Math.floor(b.getTime()/1E3),c,d,e=!1;try{d=t(document.cookie)}catch(y){d={}}d=d._fz_ssn;
(c=!d)||(c=E(),c=(new Date).getTime()>c+18E5?!1:!0,c=!c);if(!c){c=h.referrer_domain;var g=h.domain;c=!(""===c||g===c)}c||((c=E())?(c=new Date(c),g=new Date,c=c.getUTCDate()===g.getUTCDate()&&c.getUTCMonth()===g.getUTCMonth()&&c.getUTCFullYear()===g.getUTCFullYear()):c=!1,c=!c);if(c){d="";e=9;for(g=0;g<e;g++)c=10*Math.random()>>>0,d+=""+c;d=""+b+d;c=b;e=!0}else d&&"string"===typeof d?(c=d.length)&&9>=c?c=0:(c=d.substring(0,c-9),c=parseInt(c,10)):c=0;b=0<c?Math.floor(b-c):-1;try{document.cookie="_fz_ssn="+
d+"; path=/; expires="+a.toUTCString()}catch(y){}return{isNew:e,id:d,duration:b}}function F(){var b,a;try{b=t(document.cookie)}catch(c){b={}}a=b._fz_fvdt;if(!a){b=new Date;a=parseInt(b.getTime()/1E3,10);b.setFullYear(b.getFullYear()+20);try{document.cookie="_fz_fvdt="+a+"; path=/; expires="+b.toUTCString()}catch(c){}}return a}function m(b){p=r();p.id&&(b.ssn=p.id);p.isNew&&(p.isNew=!1,b.ssn_start=1);b.ssn_dr=p.duration;b.fv_date=G;b.ref=h.uri||null;b.back_ref=h.referrer||null;b.title=h.title||null;
b.scr_res=h.screen_res||null;b.hdpi=h.hdpi?1:null;var a;a=99999*Math.random()+1>>>0;a=[(new Date).getTime(),a].join("");b.ac=a;b.sv="1069";return b}function t(b){var a={},c,d,e,g;if(!b)return{};b=b.split(";");e=0;for(g=b.length;e<g;e++)if(c=b[e])c=c.split("="),1>=c.length||(d=decodeURIComponent(c[0]),d=d.trim?d.trim():d.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,""),a[d]=decodeURIComponent(c[1]));return a}function H(){return{utm_source:h.utm_source||null,utm_campaign:h.utm_campaign||
null,utm_medium:h.utm_medium||null,utm_term:h.utm_term||null,utm_content:h.utm_content||null,s1:h.s1||null,s2:h.s2||null,s3:h.s3||null,s4:h.s4||null,s5:h.s5||null,s6:h.s6||null,s7:h.s7||null,s8:h.s8||null,s9:h.s9||null,s10:h.s10||null,s11:h.s11||null,s12:h.s12||null,s13:h.s13||null,s14:h.s14||null,s15:h.s15||null,s16:h.s16||null}}function q(b,a){var c=new Image(1,1);void 0!==a&&"function"===typeof a&&(c.onload=function(){a()});c.src=b;O()}function O(){var b=(new Date).getTime(),a=new Date(b+18E5);
try{window.localStorage?window.localStorage.setItem("_fz_tr",b.toString()):document.cookie="_fz_tr="+b+"; path=/; expires="+a.toUTCString()}catch(c){}}function E(){var b;try{if(window.localStorage)return parseInt(window.localStorage.getItem("_fz_tr")||0,10);if(b=t(document.cookie))if(b=b._fz_tr)return parseInt(b,10)}catch(a){}return 0}function P(b){var a;try{a=document.cookie.match(new RegExp("(?:^|; )"+b.replace(/([\.$?*|{}\(\)\[\]\\/\+^])/g,"\$1")+"=([^;]*)"))}catch(c){}return a?decodeURIComponent(a[1]):
null}function Q(b,a){var c;if(b&&(c=R())){c.open("post",b,!0);c.setRequestHeader("X-Requested-With","XMLHttpRequest");c.setRequestHeader("Content-Type","application/x-www-form-urlencoded");c.withCredentials=!0;c.onreadystatechange=function(){switch(c.readyState){case 4:c.abort()}};try{c.send(I(a||{}))}catch(d){}}}function R(){var b=null;try{if(window.XMLHttpRequest)b=new XMLHttpRequest;else if(window.ActiveXObject)try{b=new window.ActiveXObject("Msxml2.XMLHTTP")}catch(a){b=new window.ActiveXObject("Microsoft.XMLHTTP")}}catch(a){b=
null}return b}function l(b,a){return b&&a?a?[b,I(a)].join(-1===b.indexOf("?")?"?":"&"):b:""}function I(b){var a,c,d,e=[];if(b instanceof Array)for(c=0,d=b.length;c<d;++c)e.push([b[c][0],encodeURIComponent(b[c][1])].join("="));else for(a in b)if(b.hasOwnProperty(a))if(b[a]instanceof Array)for(c=0,d=b[a].length;c<d;++c)b[a][c]&&e.push([a,encodeURIComponent(b[a][c])].join("="));else b[a]&&e.push([a,encodeURIComponent(b[a])].join("="));return e.join("&")}function A(b){var a,c,d,e;a=0;for(c=n.length;a<
c;a++)if(e=n[a],b.source===e.contentWindow&&(d=JSON.parse(b.data))){0<=d.height&&(n[a].height=d.height);if(d.setCookie)try{document.cookie=d.setCookie}catch(y){}if(d.getCookie){var g=window.JSON.stringify({getCookie:P(d.getCookie)});e&&e.contentWindow&&e.contentWindow.postMessage(g,"https://content.mql5.com/")}d.click&&(d=e&&e.parentNode)&&(d=d.getAttribute("id"))&&(e=k[d])&&(e=e.data)&&window.open(l("https://content.mql5.com/go",m({link:e.link,a:e.a,s:e.s,v:e.v,id:d,uid:e.uid})),"_blank")}}function S(b){function a(){e&&
(clearInterval(e),e=null);b()}var c=window,d=c.document,e,g,f;if(d.addEventListener)d.addEventListener("DOMContentLoaded",a,!1),c.addEventListener("load",a,!1);else if(c.attachEvent){c.attachEvent("onload",a);g=d.createElement("div");try{f=null===c.frameElement}catch(N){}g.doScroll&&f&&c.external&&(e=setInterval(function(){try{g.doScroll(),a()}catch(N){}},30))}"complete"===d.readyState&&a()}function u(){window.parent&&window.parent.postMessage&&window.parent.postMessage('{"height":'+document.body.offsetHeight+
"}","*")}var k=[],v=!1,h=D(),p=r(),G=F(),w=!0,n,f=window.fcoreobj;f||(window.FintezaCoreObject?(f=window.fcoreobj=window[window.FintezaCoreObject]||{},window.FintezaCoreObject=null):f=window.fcoreobj={});f.sv="1069, 10 Jan 2018";f.act=f.act||[];f.q=f.q||[];f._websiteId=null;f.loaded=!0;f.inited=!0;f.register=function(b){var a;if(!b||"string"!=typeof b)return null;(a=k[b])||(a=k[b]={});return a};f.finish=function(){x();return this};f.show=function(b){var a;if(!b||"string"!=typeof b)return null;
f.lead(void 0,void 0,b);a=this.register(b);a.readyToShow=!0;if(a.data)return z(b),a;x();return a};f.lead=function(b,a,c,d){if(b||c)if(a||(a="Visit"),"Visit"!==a||!v){"Visit"===a&&(v=!0);var e=H();e.event=a.split(" ").join("+");b?e.id=b:c&&(e.zid=c);q(l("https://content.mql5.com/tr",m(e)),d)}};f.leave=function(b,a,c){function d(){clearTimeout(e);f||(c&&c(),f=!0)}var e,g,f=!1;b&&a&&(g=H(),g.id=b,g.next_ref=a,q(l("https://content.mql5.com/tr",m(g)),d),setTimeout(d,500))};f.response=function(b){var a,c,d,e;if(b&&
b.b)for(b=b.b,d=0,e=b.length;d<e;d++)if(a=b[d])if(c=k[a.zone])c.data=a,c.dataLoading=!1,c.readyToShow?z(a.zone):a.format&56||C(null,a)};f.openlink=function(b){var a,c;b&&(a=window.location,c=a.href,Q(a.protocol+"//"+a.host+"/go"+c.substr(c.lastIndexOf("?"))),window.open(b))};f.routePage=function(){h=D();p=r();G=F();v=!1};f.autoHeight=function(){var b=window;b.addEventListener?b.addEventListener("resize",u,!1):b.attachEvent&&b.attachEvent("onresize",u);S(u)};(function(){var b=f.act,a;for(a=b.shift();void 0!==
a;a=b.shift())a&&"function"===typeof a&&a();f.act.push=function(a){a()}})();(function(){function b(a,c){var d;c=Array.prototype.slice.call(c);d=a[c[0]];"function"===typeof d?d.apply(null,c.slice(1)):d instanceof Object&&b(d,c.slice(1))}var a={register:{website:function(a,b,c,d,h,k){"object"===typeof a&&(b=!1!==a.sendVisit,c=a.trackHash,d=a.trackLinks,h=!1!==a.accurateBounceRate,k=a.timeOnPage,a=a.id||a.websiteId);f._websiteId=a;!1!==b&&f.lead(a);!0===c&&J();!0===d&&K();!1===h&&!0!==k||M(!0===k)},
zone:function(a){var b,c;if("[object Array]"===Object.prototype.toString.call(a))for(b=0,c=a.length;b<c;b++)f.register(a[b]);else f.register(a);f.finish()}},route:{page:function(a){f.routePage();!1!==a&&f._websiteId&&f.lead(f._websiteId)}},track:function(a,b){f._websiteId&&f.lead(f._websiteId,a,void 0,b)},show:function(a){f.show(a)}},c,d;c=f.q;for(d=c.shift();void 0!==d;d=c.shift())d&&d.length&&b.call(null,a,d);f.q.push=function(c){b.call(null,a,c)}})();(function(){var b,a;"undefined"!==typeof document.hidden?
(b="hidden",a="visibilitychange"):"undefined"!==typeof document.msHidden?(b="msHidden",a="msvisibilitychange"):"undefined"!==typeof document.webkitHidden&&(b="webkitHidden",a="webkitvisibilitychange");b&&a&&document.addEventListener(a,function(){w=!document[b]},!1)})()})(); window.fz("register", "website", { id: "abxxumbrormhxbmbglgdpzxmephackniop", trackLinks: true }); window.fz("track", "Colombia+Widget");}(function() {
   document.write("<div class='dolar-colombia-widget'><a href='https://www.dolar-colombia.com/' title='dolar hoy' style='pointer-events:auto!important'>Dólar hoy</a>: <strong>$ 3,357.82</strong></div>");
})();