<?php
include '../../modelo/conexion.php'; 
session_start();
  if(isset($_GET['copy'])){
 for($i=1;$i<=$_GET['can'];$i++){
// $res = 'select *, a.laminas from cotizaciones a, producto b  where a.id_referencia=b.id_p and a.id_cotizacion='.$_GET['copy'].' ';
//                 $row =mysqli_fetch_array(mysqli_query($conexion,$res));
      
                  
//                 $sql2 = "INSERT INTO `cotizaciones` (`cantlam`,`peso_producto`,`valor_adicional`,`rollo`,`descripcion_rollo`,`ajuste`,`id_dolar`,`descuento_g`, `ancho_temp`, `alto_temp`, `valor_temp`, `valor_c_sp`,`valor_fom`,`valor_costob`,`valor_fomp`,`pelicula`, `precio_adicional`,`precio_material`,`modulo`, `observaciones2`,`an`, `al`, `fila`, `tip`, `imagen_mas`, `imagen`, `ancho_abajo`, `ubicacion_c`, `traz_vid`, `traz_vid2`, `traz_vid3`, `traz_vid4`, `laminas`, `laminas2`, `laminas3`, `laminas4`, `install`, `id_vidrio2`, `id_vidrio3`, `id_vidrio4`, `id_vidrio5`, `id_vidrio6`,`tipo_c`, `duracion`, `horizontales`,`verticales`,`desc`, `observaciones`, `hojas`, `cuerpo`, `color_ta`, `porcentaje`, `porcentaje_mp`, `per`, `boq`, `cod_traz`, `linea_cot`, `id_cot`, `cierre`, `id_referencia`, `id_vidrio`, `ancho_c`, `alto_c`, `valor_c`, `cant_restante`, `cantidad_c`, `id_cliente`, `estado_c`, `registrado_por_c` , `d1`, `id2_vidrio`, `id2_vidrio2`, `id2_vidrio3`, `id2_vidrio4`, `id2_vidrio5`, `id3_vidrio`, `id3_vidrio2`, `id3_vidrio3`, `id3_vidrio4`, `id3_vidrio5`, `id4_vidrio`, `id4_vidrio2`, `id4_vidrio3`, `id4_vidrio4`, `id4_vidrio5`)";
//                 $sql2.= "VALUES ('".$row['cantlam']."','".$row['peso_producto']."','".$row['valor_adicional']."','".$row['rollo']."','".$row['descripcion_rollo']."','".$row['ajuste']."','".$row['id_dolar']."','".$row['descuento_g']."', '".$row['ancho_temp']."','".$row['alto_temp']."','".$row['valor_temp']."','".$row['valor_c_sp']."','".$row['valor_fom']."','".$row['valor_costob']."','".$row['valor_fomp']."','".$row['pelicula']."', '".$row['precio_adicional']."','".$row['precio_material']."','".$row['modulo']."', '".$row['observaciones2']."','".$row['an']."','".$row['al']."','".$row['fila']."','".$row['tip']."','".$row['imagen_mas']."','".$row['imagen']."','".$row['ancho_abajo']."', '".$row['ubicacion_c']."', '".$row['traz_vid']."', '".$row['traz_vid2']."', '".$row['traz_vid3']."', '".$row['traz_vid4']."', '".$row['laminas']."', '".$row['laminas2']."', '".$row['laminas3']."', '".$row['laminas4']."', '".$row['install']."', '".$row['id_vidrio2']."', '".$row['id_vidrio3']."', '".$row['id_vidrio4']."', '".$row['id_vidrio5']."', '".$row['id_vidrio6']."','".$row['tipo_c']."', '".$row['duracion']."', '".$row['horizontales']."', '".$row['verticales']."','".$row['desc']."', '".$row['observaciones']."', '".$row['hojas']."', '".$row['cuerpo']."', '".$row['color_ta']."', '".$row['porcentaje']."', '".$row['porcentaje_mp']."', '".$row['per']."', '".$row['boq']."','".$row['cod_traz']."', '".$row['linea_cot']."', '".$_GET['cot']."', '".$row['cierre']."', '".$row['id_referencia']."', '".$row['id_vidrio']."', '".$row['ancho_c']."', '".$row['alto_c']."',  '".$row['valor_c']."',  '".$row['cantidad_c']."', 🤢  '".$row['cantidad_c']."', '".$row['id_cliente']."', 'En proceso', '".$_SESSION['k_username']."', '".$row['d1']."', '".$row['id2_vidrio']."', '".$row['id2_vidrio2']."', '".$row['id2_vidrio3']."', '".$row['id2_vidrio4']."', '".$row['id2_vidrio5']."', '".$row['id3_vidrio']."', '".$row['id3_vidrio2']."', '".$row['id3_vidrio3']."', '".$row['id3_vidrio4']."', '".$row['id3_vidrio5']."', '".$row['id4_vidrio']."', '".$row['id4_vidrio2']."', '".$row['id4_vidrio3']."', '".$row['id4_vidrio4']."', '".$row['id4_vidrio5']."')";
//                 mysqli_query($conexion,$sql2);
                 
                $error = mysqli_query($conexion,"insert into cotizaciones (`imagen`, `id_cot`, `id_referencia`, `laminas`, `laminas2`, `laminas3`, `laminas4`, `id_vidrio`, `id_vidrio2`, `id_vidrio3`, `id_vidrio4`, `id_vidrio5`, `id_vidrio6`, `cierre`, `ancho_c`, `ancho_c_original`, `alto_c`, `ancho_abajo`, `hojas`, `cuerpo`, `lado`, `cantidad_c`, `cantidad_temp`, `cant_restante`, `valor_c`, `valor_c_sp`, `valor_fom`, `valor_costob`, `valor_fomp`, `id_cliente`, `tipo_c`, `fecha_c`, `estado_c`, `registrado_por_c`, `aprobado`, `num_pedido`, `orden`, `asignado_a`, `linea_cot`, `cod_traz`, `boq`, `per`, `porcentaje`, `porcentaje_mp`, `descuento_g`, `color_ta`, `precio_item`, `precio_adicional`, `precio_material`, `precio_fom_sp`, `observaciones`, `observaciones2`, `desc`, `verticales`, `horizontales`, `d1`, `duracion`, `install`, `traz_vid`, `traz_vid2`, `traz_vid3`, `traz_vid4`, `ubicacion_c`, `tip`, `imagen_mas`, `an`, `al`, `fila`, `id2_vidrio`, `id2_vidrio2`, `id2_vidrio3`, `id2_vidrio4`, `id2_vidrio5`, `id3_vidrio`, `id3_vidrio2`, `id3_vidrio3`, `id3_vidrio4`, `id3_vidrio5`, `id4_vidrio`, `id4_vidrio2`, `id4_vidrio3`, `id4_vidrio4`, `id4_vidrio5`, `modulo`, `pelicula`, `huacal`, `ancho_temp`, `alto_temp`, `valor_temp`, `id_dolar`, `p_act_sp`, `p_act_cp`, `aprobado_por`, `servicio`, `estado_item`, `aprobado_por_user`, `fecha_aprobada`, `iva`, `ajuste`, `msg`, `msg2`, `peso_producto`, `valor_adicional`, `adicional_per`, `rollo`, `descripcion_rollo`, `cont_item`, `cantlam`, `poli`, `poli_v`, `poli_h`, `verpoli`, `rieles`, `alfajia`, `rejillas`, `cierres`, `rodajas`, `bisagras`, `can_rieles`, `can_alfajia`, `can_rejillas`, `can_cierres`, `can_rodajas`, `can_bisagras`, `poralu`, `porvid`, `poracc`, `porace`, `id_compuesto`, `compuestos`, `termovid1`, `termovid2`, `termovid3`, `termovid4`, `idespaciador`, `cantespaciador`,`id_dolar_actual`,`cobro`,`brazos`,`can_brazos`,`descripciones`,`vidrios`)"
                                                    . " select  `imagen`, `id_cot`, `id_referencia`, `laminas`, `laminas2`, `laminas3`, `laminas4`, `id_vidrio`, `id_vidrio2`, `id_vidrio3`, `id_vidrio4`, `id_vidrio5`, `id_vidrio6`, `cierre`, `ancho_c`, `ancho_c_original`, `alto_c`, `ancho_abajo`, `hojas`, `cuerpo`, `lado`, `cantidad_c`, `cantidad_temp`, `cant_restante`, `valor_c`, `valor_c_sp`, `valor_fom`, `valor_costob`, `valor_fomp`, `id_cliente`, `tipo_c`, `fecha_c`, `estado_c`, `registrado_por_c`, `aprobado`, `num_pedido`, `orden`, `asignado_a`, `linea_cot`, `cod_traz`, `boq`, `per`, `porcentaje`, `porcentaje_mp`, `descuento_g`, `color_ta`, `precio_item`, `precio_adicional`, `precio_material`, `precio_fom_sp`, `observaciones`, `observaciones2`, `desc`, `verticales`, `horizontales`, `d1`, `duracion`, `install`, `traz_vid`, `traz_vid2`, `traz_vid3`, `traz_vid4`, `ubicacion_c`, `tip`, `imagen_mas`, `an`, `al`, `fila`, `id2_vidrio`, `id2_vidrio2`, `id2_vidrio3`, `id2_vidrio4`, `id2_vidrio5`, `id3_vidrio`, `id3_vidrio2`, `id3_vidrio3`, `id3_vidrio4`, `id3_vidrio5`, `id4_vidrio`, `id4_vidrio2`, `id4_vidrio3`, `id4_vidrio4`, `id4_vidrio5`, `modulo`, `pelicula`, `huacal`, `ancho_temp`, `alto_temp`, `valor_temp`, `id_dolar`, `p_act_sp`, `p_act_cp`, `aprobado_por`, `servicio`, `estado_item`, `aprobado_por_user`, `fecha_aprobada`, `iva`, `ajuste`, `msg`, `msg2`, `peso_producto`, `valor_adicional`, `adicional_per`, `rollo`, `descripcion_rollo`, `cont_item`, `cantlam`, `poli`, `poli_v`, `poli_h`, `verpoli`, `rieles`, `alfajia`, `rejillas`, `cierres`, `rodajas`, `bisagras`, `can_rieles`, `can_alfajia`, `can_rejillas`, `can_cierres`, `can_rodajas`, `can_bisagras`, `poralu`, `porvid`, `poracc`, `porace`, `id_compuesto`, `compuestos`, `termovid1`, `termovid2`, `termovid3`, `termovid4`, `idespaciador`, `cantespaciador`,`id_dolar_actual`,`cobro`,`brazos`,`can_brazos`,`descripciones`,`vidrios` from cotizaciones where id_cotizacion='".$_GET['copy']."' ") ;
                 
                 $sql5 = "SELECT max(id_cotizacion) FROM cotizaciones";
                 $fila5 =mysqli_fetch_array(mysqli_query($conexion,$sql5));
                 $maxcot= $fila5["max(id_cotizacion)"];
                 
                 mysqli_query($conexion,"insert into cotizaciones (`imagen`, `id_cot`, `id_referencia`, `laminas`, `laminas2`, `laminas3`, `laminas4`, `id_vidrio`, `id_vidrio2`, `id_vidrio3`, `id_vidrio4`, `id_vidrio5`, `id_vidrio6`, `cierre`, `ancho_c`, `ancho_c_original`, `alto_c`, `ancho_abajo`, `hojas`, `cuerpo`, `lado`, `cantidad_c`, `cantidad_temp`, `cant_restante`, `valor_c`, `valor_c_sp`, `valor_fom`, `valor_costob`, `valor_fomp`, `id_cliente`, `tipo_c`, `fecha_c`, `estado_c`, `registrado_por_c`, `aprobado`, `num_pedido`, `orden`, `asignado_a`, `linea_cot`, `cod_traz`, `boq`, `per`, `porcentaje`, `porcentaje_mp`, `descuento_g`, `color_ta`, `precio_item`, `precio_adicional`, `precio_material`, `precio_fom_sp`, `observaciones`, `observaciones2`, `desc`, `verticales`, `horizontales`, `d1`, `duracion`, `install`, `traz_vid`, `traz_vid2`, `traz_vid3`, `traz_vid4`, `ubicacion_c`, `tip`, `imagen_mas`, `an`, `al`, `fila`, `id2_vidrio`, `id2_vidrio2`, `id2_vidrio3`, `id2_vidrio4`, `id2_vidrio5`, `id3_vidrio`, `id3_vidrio2`, `id3_vidrio3`, `id3_vidrio4`, `id3_vidrio5`, `id4_vidrio`, `id4_vidrio2`, `id4_vidrio3`, `id4_vidrio4`, `id4_vidrio5`, `modulo`, `pelicula`, `huacal`, `ancho_temp`, `alto_temp`, `valor_temp`, `id_dolar`, `p_act_sp`, `p_act_cp`, `aprobado_por`, `servicio`, `estado_item`, `aprobado_por_user`, `fecha_aprobada`, `iva`, `ajuste`, `msg`, `msg2`, `peso_producto`, `valor_adicional`, `adicional_per`, `rollo`, `descripcion_rollo`, `cont_item`, `cantlam`, `poli`, `poli_v`, `poli_h`, `verpoli`, `rieles`, `alfajia`, `rejillas`, `cierres`, `rodajas`, `bisagras`, `can_rieles`, `can_alfajia`, `can_rejillas`, `can_cierres`, `can_rodajas`, `can_bisagras`, `poralu`, `porvid`, `poracc`, `porace`, `id_compuesto`, `compuestos`, `termovid1`, `termovid2`, `termovid3`, `termovid4`, `idespaciador`, `cantespaciador`,`id_dolar_actual`,`cobro`,`brazos`,`can_brazos`,`descripciones`,`vidrios`) "
                                             . "select  `imagen`, `id_cot`, `id_referencia`, `laminas`, `laminas2`, `laminas3`, `laminas4`, `id_vidrio`, `id_vidrio2`, `id_vidrio3`, `id_vidrio4`, `id_vidrio5`, `id_vidrio6`, `cierre`, `ancho_c`, `ancho_c_original`, `alto_c`, `ancho_abajo`, `hojas`, `cuerpo`, `lado`, `cantidad_c`, `cantidad_temp`, `cant_restante`, `valor_c`, `valor_c_sp`, `valor_fom`, `valor_costob`, `valor_fomp`, `id_cliente`, `tipo_c`, `fecha_c`, `estado_c`, `registrado_por_c`, `aprobado`, `num_pedido`, `orden`, `asignado_a`, `linea_cot`, `cod_traz`, `boq`, `per`, `porcentaje`, `porcentaje_mp`, `descuento_g`, `color_ta`, `precio_item`, `precio_adicional`, `precio_material`, `precio_fom_sp`, `observaciones`, `observaciones2`, `desc`, `verticales`, `horizontales`, `d1`, `duracion`, `install`, `traz_vid`, `traz_vid2`, `traz_vid3`, `traz_vid4`, `ubicacion_c`, `tip`, `imagen_mas`, `an`, `al`, `fila`, `id2_vidrio`, `id2_vidrio2`, `id2_vidrio3`, `id2_vidrio4`, `id2_vidrio5`, `id3_vidrio`, `id3_vidrio2`, `id3_vidrio3`, `id3_vidrio4`, `id3_vidrio5`, `id4_vidrio`, `id4_vidrio2`, `id4_vidrio3`, `id4_vidrio4`, `id4_vidrio5`, `modulo`, `pelicula`, `huacal`, `ancho_temp`, `alto_temp`, `valor_temp`, `id_dolar`, `p_act_sp`, `p_act_cp`, `aprobado_por`, `servicio`, `estado_item`, `aprobado_por_user`, `fecha_aprobada`, `iva`, `ajuste`, `msg`, `msg2`, `peso_producto`, `valor_adicional`, `adicional_per`, `rollo`, `descripcion_rollo`, `cont_item`, `cantlam`, `poli`, `poli_v`, `poli_h`, `verpoli`, `rieles`, `alfajia`, `rejillas`, `cierres`, `rodajas`, `bisagras`, `can_rieles`, `can_alfajia`, `can_rejillas`, `can_cierres`, `can_rodajas`, `can_bisagras`, `poralu`, `porvid`, `poracc`, `porace`, '$maxcot', `compuestos`, `termovid1`, `termovid2`, `termovid3`, `termovid4`, `idespaciador`, `cantespaciador`,`id_dolar_actual`,`cobro`,`brazos`,`can_brazos`,`descripciones`,`vidrios` from cotizaciones where id_compuesto='".$_GET['copy']."' ");
                 
                 
                 //se consultan los servicios
                 $request_ser=mysqli_query($conexion,"SELECT * FROM referencia_mo a, cotizaciones_servicios b where a.id_ref_mo=b.id_servicio and b.id_cotizacion=".$_GET['cot']." and b.id_cot_mas=".$_GET['copy']." ");
                 while($row2=mysqli_fetch_array($request_ser))
	         {
                     $sql = "INSERT INTO `cotizaciones_servicios` (`obs_servicio`, `id_cot_mas`, `id_cotizacion`, `id_servicio`, `cantidad_serv`, `descuento_serv`, `precio_servicio`)";
                     $sql.= "VALUES ('".$row2['obs_servicio']."', '".$maxcot."', '".$_GET['cot']."', '".$row2['id_servicio']."', '".$row2['cantidad_serv']."', '".$row2['descuento_serv']."', '".$row2['precio_servicio']."')";
                     mysqli_query($conexion,$sql);
                     
                 }
                
                 //se consultan los compuestos de esta referencia  -- parte de los materi prima
                 $request_acc=mysqli_query($conexion,"SELECT * FROM referencia_acce a, referencias b where a.num_ref=b.id_referencia and a.cotizacion=".$_GET["cot"]." and a.id_cot=".$_GET['copy']."  ");
                 while($row3=mysqli_fetch_array($request_acc))
                 {  
                     $sql33 = "INSERT INTO `referencia_acce` (`cotizacion`, `num_ref`, `id_cot`, `cantidad_m`, `calcular`, `metro`, `yes`, `lado`, `med`)";
                     $sql33.= "VALUES ('".$_GET["cot"]."', '".$row3['num_ref']."', '".$maxcot."',  '".$row3['cantidad_m']."', '".$row3['calcular']."', '".$row3['metro']."', '".$row3['yes']."', '".$row3['lado']."', '".$row3['med']."')";
                     mysqli_query($conexion,$sql33);
                 }
                 // se agrega los kit 
                 $request_kit=mysqli_query($conexion,"SELECT * FROM producto a, cotizaciones_kit b where a.id_p=b.id_producto and b.id_cot=".$_GET['cot']." and b.id_prod_mas=".$_GET['copy']." and b.comp='1' ");
                 while($row5=mysqli_fetch_array($request_kit))
                 {   
                     $sql3 = "INSERT INTO `cotizaciones_kit` (`id_producto`, `id_cot`, `cantidad_k`, `por_k`, `desc_k`, `id_prod_mas`, `color_k`, `comp`)";
                     $sql3.= "VALUES ('".$row5['id_producto']."', '".$_GET["cot"]."', '".$row5['cantidad_k']."', '".$row5['por_k']."',  '".$row3['desc_k']."', '".$maxcot."', '".$row5['color_k']."', '".$row5['comp']."')";
                     mysqli_query($conexion,$sql3);

                 }
                 
                 // se agrega los compuesto
                  $request2=mysqli_query($conexion,"SELECT * FROM producto a, cotizaciones_sub c where c.id_referencia_sub=a.id_p and c.id_cot_sub=".$_GET["cot"]." and c.id_producto_cot=".$_GET['copy']."");
                  while($row4=mysqli_fetch_array($request2))
	          {  
                     $sql4 = "INSERT INTO `cotizaciones_sub` (`id_dolar`,`rollo`,`descripcion_rollo`,`pelicula`, `valor_fom_sub`,`valor_sp`,`valor_fom_sp`,`imagen_adic`, `imagen_sub`,`laminas`,`laminas2`,`laminas3`,`laminas4`, `tipo_c_sub`, `install`, `horizontales`,`verticales`,`desc_sub`, `observaciones_sub`, `hojas_sub`, `cuerpo_sub`, `color_ta_sub`, `porcentaje_sub`, `porcentaje_mp_sub`, `per_sub`, `boq_sub`, `cod_traz_sub`, `linea_cot_sub`, `id_cot_sub`, `cierre_sub`, `id_referencia_sub`, `id_vidrio_sub`, `id_vidrio_sub2`, `id_vidrio_sub3`, `id_vidrio_sub4`, `id_vidrio_sub5`, `id_vidrio_sub6`, `ancho_c_sub`, `alto_c_sub`, `valor_c_sub`, `cantidad_c_sub`, `cant_restante`, `id_cliente_sub`, `estado_c_sub`, `registrado_por_c_sub`, `id_producto_cot`, `d1`, `id2_vidrio`, `id2_vidrio2`, `id2_vidrio3`, `id2_vidrio4`, `id2_vidrio5`, `id3_vidrio`, `id3_vidrio2`, `id3_vidrio3`, `id3_vidrio4`, `id3_vidrio5`, `id4_vidrio`, `id4_vidrio2`, `id4_vidrio3`, `id4_vidrio4`, `id4_vidrio5`, `traz_vid`, `traz_vid2`, `traz_vid3`, `traz_vid4`)";
                     $sql4.= "VALUES ('".$row4['id_dolar']."','".$row4['rollo']."','".$row4['descripcion_rollo']."','".$row4['pelicula']."','".$row4['valor_fom_sub']."','".$row4['valor_sp']."','".$row4['valor_fom_sp']."','".$row4['imagen_adic']."', '".$row4['imagen_sub']."', '".$row4['laminas']."', '".$row4['laminas2']."', '".$row4['laminas3']."', '".$row4['laminas4']."', '".$row4['tipo_c_sub']."', '".$row4['install']."','".$row4['horizontales']."', '".$row4['verticales']."','".$row4['desc_sub']."', '".$row4['observaciones_sub']."', '".$row4['hojas_sub']."', '".$row4['cuerpo_sub']."', '".$row4['color_ta_sub']."', '".$row4['porcentaje_sub']."', '".$row4['porcentaje_mp_sub']."', '".$row4['per_sub']."','".$row4['boq_sub']."', '".$row4['cod_traz_sub']."', '".$row4['linea_cot_sub']."', '".$_GET["cot"]."', '".$row4['cierre_sub']."', '".$row4['id_referencia_sub']."', '".$row4['id_vidrio_sub']."', '".$row4['id_vidrio_sub2']."', '".$row4['id_vidrio_sub3']."', '".$row4['id_vidrio_sub4']."', '".$row4['id_vidrio_sub5']."', '".$row4['id_vidrio_sub6']."', '".$row4['ancho_c_sub']."',  '".$row4['alto_c_sub']."',  '".$row4['valor_c_sub']."',  '".$row4['cantidad_c_sub']."', '".$row4['cantidad_c_sub']."', '".$row4['id_cliente_sub']."', '".$row4['estado_c_sub']."', '".$_SESSION['k_username']."', '".$maxcot."', '".$row4['d1']."', '".$row4['id2_vidrio']."', '".$row4['id2_vidrio2']."', '".$row4['id2_vidrio3']."', '".$row4['id2_vidrio4']."', '".$row4['id2_vidrio5']."', '".$row4['id3_vidrio']."', '".$row4['id3_vidrio2']."', '".$row4['id3_vidrio3']."', '".$row4['id3_vidrio4']."', '".$row4['id3_vidrio5']."', '".$row4['id4_vidrio']."', '".$row4['id4_vidrio2']."', '".$row4['id4_vidrio3']."', '".$row4['id4_vidrio4']."', '".$row4['id4_vidrio5']."', '".$row4['traz_vid']."', '".$row4['traz_vid2']."', '".$row4['traz_vid3']."', '".$row4['traz_vid4']."')";
                     mysqli_query($conexion,$sql4);
                      
                  }
 }
     echo 'Se ha Copiado el items  con exito :) '.$error; 
                       

}   

